# fly.toml app configuration file generated for old-glade-1875 on 2023-07-25T18:51:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "old-glade-1875"
primary_region = "ams"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
